
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1361/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:172 (project)"
    message: |
      The target system is: Generic -  - 
      The host system is: Linux - 5.15.0-1051-aws - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1361/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/snap/cmake/1361/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/snap/cmake/1361/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:172 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /opt/armcompiler/bin/armclang 
      Build flags: -mcpu=Cortex-M55;-mfloat-abi=hard
      Id flags:  
      
      The output was:
      1
      armclang: fatal error: no target architecture given; use --target=arm-arm-none-eabi or --target=aarch64-arm-none-eabi
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1361/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/snap/cmake/1361/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/snap/cmake/1361/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:172 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /opt/armcompiler/bin/armclang 
      Build flags: -mcpu=Cortex-M55;-mfloat-abi=hard
      Id flags: -c 
      
      The output was:
      1
      armclang: fatal error: no target architecture given; use --target=arm-arm-none-eabi or --target=aarch64-arm-none-eabi
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1361/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/snap/cmake/1361/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/snap/cmake/1361/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:172 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /opt/armcompiler/bin/armclang 
      Build flags: -mcpu=Cortex-M55;-mfloat-abi=hard
      Id flags: -Aa 
      
      The output was:
      1
      armclang: fatal error: no target architecture given; use --target=arm-arm-none-eabi or --target=aarch64-arm-none-eabi
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1361/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/snap/cmake/1361/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/snap/cmake/1361/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:172 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /opt/armcompiler/bin/armclang 
      Build flags: -mcpu=Cortex-M55;-mfloat-abi=hard
      Id flags: -D__CLASSIC_C__ 
      
      The output was:
      1
      armclang: fatal error: no target architecture given; use --target=arm-arm-none-eabi or --target=aarch64-arm-none-eabi
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1361/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/snap/cmake/1361/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/snap/cmake/1361/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:172 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /opt/armcompiler/bin/armclang 
      Build flags: -mcpu=Cortex-M55;-mfloat-abi=hard
      Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is ARMClang, found in:
        /home/ubuntu/Paddle-examples-for-AVH/object_detection/tmp/object_detection/PicodetM55/CMakeFiles/3.28.1/CompilerIdC/a.out
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/snap/cmake/1361/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/snap/cmake/1361/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:172 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/home/ubuntu/Paddle-examples-for-AVH/object_detection/tmp/object_detection/PicodetM55/CMakeFiles/CMakeScratch/TryCompile-40lbSt"
      binary: "/home/ubuntu/Paddle-examples-for-AVH/object_detection/tmp/object_detection/PicodetM55/CMakeFiles/CMakeScratch/TryCompile-40lbSt"
    cmakeVariables:
      CMAKE_C_COMPILER_TARGET: "arm-arm-none-eabi"
      CMAKE_C_FLAGS: "-mcpu=Cortex-M55 -mfloat-abi=hard"
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/opt/ctools/etc/CMakeASM"
      CMAKE_WARN_DEPRECATED: "FALSE"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/home/ubuntu/Paddle-examples-for-AVH/object_detection/tmp/object_detection/PicodetM55/CMakeFiles/CMakeScratch/TryCompile-40lbSt'
        
        Run Build Command(s): /usr/bin/ninja -v cmTC_a8f47
        [1/2] /opt/armcompiler/bin/armclang --target=arm-arm-none-eabi   -mcpu=Cortex-M55 -mfloat-abi=hard    -v -MD -MT CMakeFiles/cmTC_a8f47.dir/CMakeCCompilerABI.o -MF CMakeFiles/cmTC_a8f47.dir/CMakeCCompilerABI.o.d -o CMakeFiles/cmTC_a8f47.dir/CMakeCCompilerABI.o -c /snap/cmake/1361/share/cmake-3.28/Modules/CMakeCCompilerABI.c
        Product: Arm Compiler for Embedded 6.18 Professional
        Component: Arm Compiler for Embedded 6.18
        Tool: armclang [5e4cc700]
        
        Target: arm-arm-none-eabi
         (in-process)
         "/opt/armcompiler/bin/armclang" -cc1 -triple thumbv8.1m.main-arm-none-eabihf -emit-obj -mrelax-all --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model static -mframe-pointer=none -menable-no-infs -menable-no-nans -fmath-errno -fno-signed-zeros -fdenormal-fp-math=preserve-sign,preserve-sign -fdenormal-fp-math-f32=ieee,ieee -ffp-contract=on -fno-rounding-math -ffinite-math-only -mconstructor-aliases -target-cpu cortex-m55 -target-feature +vfp2 -target-feature +vfp2sp -target-feature -vfp3 -target-feature +vfp3d16 -target-feature +vfp3d16sp -target-feature -vfp3sp -target-feature +fp16 -target-feature -vfp4 -target-feature +vfp4d16 -target-feature +vfp4d16sp -target-feature -vfp4sp -target-feature -fp-armv8 -target-feature +fp-armv8d16 -target-feature +fp-armv8d16sp -target-feature -fp-armv8sp -target-feature +fullfp16 -target-feature +fp64 -target-feature -d32 -target-feature -neon -target-feature -sha2 -target-feature -aes -target-abi aapcs -mfloat-abi hard -fallow-half-arguments-and-returns -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -fforce-dwarf-frame -v -ffunction-sections -fdata-sections -fcoverage-compilation-dir=/home/ubuntu/Paddle-examples-for-AVH/object_detection/tmp/object_detection/PicodetM55/CMakeFiles/CMakeScratch/TryCompile-40lbSt -resource-dir /opt/armcompiler/lib/clang/15.0.0 -dependency-file CMakeFiles/cmTC_a8f47.dir/CMakeCCompilerABI.o.d -MT CMakeFiles/cmTC_a8f47.dir/CMakeCCompilerABI.o -sys-header-deps -internal-isystem /opt/armcompiler/bin/../include -nobuiltininc -Wno-license-management -fdebug-compilation-dir=/home/ubuntu/Paddle-examples-for-AVH/object_detection/tmp/object_detection/PicodetM55/CMakeFiles/CMakeScratch/TryCompile-40lbSt -ferror-limit 19 -fvisibility hidden -fno-signed-char -fgnuc-version=4.2.1 -fsuppress-licensing -aggressive-jump-threading -o CMakeFiles/cmTC_a8f47.dir/CMakeCCompilerABI.o -x c /snap/cmake/1361/share/cmake-3.28/Modules/CMakeCCompilerABI.c
        Arm Compiler for Embedded 6.18 -cc1 default target aarch64-arm-none-eabi
        #include "..." search starts here:
        #include <...> search starts here:
         /opt/armcompiler/bin/../include
        End of search list.
        [2/2] : && armar --create -cr libcmTC_a8f47.a  CMakeFiles/cmTC_a8f47.dir/CMakeCCompilerABI.o && :
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1361/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:127 (message)"
      - "/snap/cmake/1361/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:172 (project)"
    message: |
      Parsed C implicit include dir info: rv=done
        found start of include info
        found start of implicit include info
          add: [/opt/armcompiler/bin/../include]
        end of search list found
        collapse include dir [/opt/armcompiler/bin/../include] ==> [/opt/armcompiler/include]
        implicit include dirs: [/opt/armcompiler/include]
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1361/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:159 (message)"
      - "/snap/cmake/1361/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:172 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(armlink|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        ignore line: [Change Dir: '/home/ubuntu/Paddle-examples-for-AVH/object_detection/tmp/object_detection/PicodetM55/CMakeFiles/CMakeScratch/TryCompile-40lbSt']
        ignore line: []
        ignore line: [Run Build Command(s): /usr/bin/ninja -v cmTC_a8f47]
        ignore line: [[1/2] /opt/armcompiler/bin/armclang --target=arm-arm-none-eabi   -mcpu=Cortex-M55 -mfloat-abi=hard    -v -MD -MT CMakeFiles/cmTC_a8f47.dir/CMakeCCompilerABI.o -MF CMakeFiles/cmTC_a8f47.dir/CMakeCCompilerABI.o.d -o CMakeFiles/cmTC_a8f47.dir/CMakeCCompilerABI.o -c /snap/cmake/1361/share/cmake-3.28/Modules/CMakeCCompilerABI.c]
        ignore line: [Product: Arm Compiler for Embedded 6.18 Professional]
        ignore line: [Component: Arm Compiler for Embedded 6.18]
        ignore line: [Tool: armclang [5e4cc700]]
        ignore line: []
        ignore line: [Target: arm-arm-none-eabi]
        ignore line: [ (in-process)]
        ignore line: [ "/opt/armcompiler/bin/armclang" -cc1 -triple thumbv8.1m.main-arm-none-eabihf -emit-obj -mrelax-all --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model static -mframe-pointer=none -menable-no-infs -menable-no-nans -fmath-errno -fno-signed-zeros -fdenormal-fp-math=preserve-sign preserve-sign -fdenormal-fp-math-f32=ieee ieee -ffp-contract=on -fno-rounding-math -ffinite-math-only -mconstructor-aliases -target-cpu cortex-m55 -target-feature +vfp2 -target-feature +vfp2sp -target-feature -vfp3 -target-feature +vfp3d16 -target-feature +vfp3d16sp -target-feature -vfp3sp -target-feature +fp16 -target-feature -vfp4 -target-feature +vfp4d16 -target-feature +vfp4d16sp -target-feature -vfp4sp -target-feature -fp-armv8 -target-feature +fp-armv8d16 -target-feature +fp-armv8d16sp -target-feature -fp-armv8sp -target-feature +fullfp16 -target-feature +fp64 -target-feature -d32 -target-feature -neon -target-feature -sha2 -target-feature -aes -target-abi aapcs -mfloat-abi hard -fallow-half-arguments-and-returns -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -fforce-dwarf-frame -v -ffunction-sections -fdata-sections -fcoverage-compilation-dir=/home/ubuntu/Paddle-examples-for-AVH/object_detection/tmp/object_detection/PicodetM55/CMakeFiles/CMakeScratch/TryCompile-40lbSt -resource-dir /opt/armcompiler/lib/clang/15.0.0 -dependency-file CMakeFiles/cmTC_a8f47.dir/CMakeCCompilerABI.o.d -MT CMakeFiles/cmTC_a8f47.dir/CMakeCCompilerABI.o -sys-header-deps -internal-isystem /opt/armcompiler/bin/../include -nobuiltininc -Wno-license-management -fdebug-compilation-dir=/home/ubuntu/Paddle-examples-for-AVH/object_detection/tmp/object_detection/PicodetM55/CMakeFiles/CMakeScratch/TryCompile-40lbSt -ferror-limit 19 -fvisibility hidden -fno-signed-char -fgnuc-version=4.2.1 -fsuppress-licensing -aggressive-jump-threading -o CMakeFiles/cmTC_a8f47.dir/CMakeCCompilerABI.o -x c /snap/cmake/1361/share/cmake-3.28/Modules/CMakeCCompilerABI.c]
        ignore line: [Arm Compiler for Embedded 6.18 -cc1 default target aarch64-arm-none-eabi]
        ignore line: [#include "..." search starts here:]
        ignore line: [#include <...> search starts here:]
        ignore line: [ /opt/armcompiler/bin/../include]
        ignore line: [End of search list.]
        ignore line: [[2/2] : && armar --create -cr libcmTC_a8f47.a  CMakeFiles/cmTC_a8f47.dir/CMakeCCompilerABI.o && :]
        ignore line: []
        ignore line: []
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
...
