if (CMAKE_SYSTEM_PROCESSOR STREQUAL "cortex-m33")
    set(ARM_CPU "ARMCM33")
elseif (CMAKE_SYSTEM_PROCESSOR STREQUAL "cortex-m55")
    set(ARM_CPU "ARMCM55")
elseif (CMAKE_SYSTEM_PROCESSOR STREQUAL "cortex-m85")
    set(ARM_CPU "ARMCM85")
endif ()
add_definitions(-D${ARM_CPU})

set(CMSIS_PATH ${ETHOSU_PATH}/cmsis)

set(CMSIS_DEVICE_PATH "${CMSIS_PATH}/Device/ARM/${ARM_CPU}")
set(CMSIS_DEVICE_INCLUDE_PATH ${CMSIS_DEVICE_PATH}/Include)
INCLUDE_DIRECTORIES(${CMSIS_DEVICE_INCLUDE_PATH})
set(CMSIS_DEVICE_SOURCE_PATH ${CMSIS_DEVICE_PATH}/Source)
file(GLOB CMSIS_STARTUP_SRCS "${CMSIS_DEVICE_SOURCE_PATH}/*.c")
add_library(cmsis_startup STATIC ${CMSIS_STARTUP_SRCS})

set(CMSIS_CORE_INCLUDE_PATH "${CMSIS_PATH}/CMSIS/Core/Include")
INCLUDE_DIRECTORIES(${CMSIS_CORE_INCLUDE_PATH})

set(CMSIS_NN_PATH "${CMSIS_PATH}/CMSIS/NN")
set(CMSIS_NN_SOURCE_PATH "${CMSIS_NN_PATH}/Source")
set(CMSIS_NN_INCLUDE_PATH "${CMSIS_NN_PATH}/Include")
INCLUDE_DIRECTORIES(${CMSIS_NN_INCLUDE_PATH})
file(GLOB CMSIS_NN_SRCS "${CMSIS_NN_SOURCE_PATH}/*/*.c")
add_library(cmsis_nn STATIC ${CMSIS_NN_SRCS})

set(CMSIS_DSP_INCLUDE_PATH "${CMSIS_PATH}/CMSIS/DSP/Include")
INCLUDE_DIRECTORIES(${CMSIS_DSP_INCLUDE_PATH})


set(CMSIS_LIBS "")
list(APPEND CMSIS_LIBS cmsis_startup cmsis_nn)

message("****************************** CMSIS OPTIONS ******************************")
message("ARM_CPU is ${ARM_CPU}")

message("CMSIS_PATH is ${CMSIS_PATH}")

message("CMSIS_DEVICE_PATH is ${CMSIS_DEVICE_PATH}")
message("CMSIS_DEVICE_SOURCE_PATH is ${CMSIS_DEVICE_SOURCE_PATH}")
message("CMSIS_DEVICE_INCLUDE_PATH is ${CMSIS_DEVICE_INCLUDE_PATH}")

message("CMSIS_CORE_INCLUDE_PATH is ${CMSIS_CORE_INCLUDE_PATH}")

message(CMSIS_NN_PATH is ${CMSIS_NN_PATH})
message("CMSIS_NN_SOURCE_PATH is ${CMSIS_NN_SOURCE_PATH}")
message("CMSIS_NN_INCLUDE_PATH is ${CMSIS_NN_INCLUDE_PATH}")

message("CMSIS_DSP_INCLUDE_PATH is ${CMSIS_DSP_INCLUDE_PATH}")
message("****************************** CMSIS OPTIONS ******************************")