set(ETHOSU_PLATFORM_PATH ${ETHOSU_PATH}/core_platform)

if (CMAKE_SYSTEM_PROCESSOR STREQUAL "cortex-m55")
    set(CORSTONE_NAME "corstone-300")
elseif (CMAKE_SYSTEM_PROCESSOR STREQUAL "cortex-m85")
    set(CORSTONE_NAME "corstone-310")
endif ()

set(CORSTONE_PATH ${ETHOSU_PLATFORM_PATH}/targets/${CORSTONE_NAME})
file(GLOB CORSTONE_SRCS "${CORSTONE_PATH}/*.c")

set(CORSTONE_LD ${CMAKE_CURRENT_SOURCE_DIR}/${CORSTONE_NAME}.ld)

INCLUDE_DIRECTORIES(${ETHOSU_PLATFORM_PATH}/drivers/uart/include)
add_subdirectory(${ETHOSU_PLATFORM_PATH}/drivers/uart uart)

set(CORE_PLATFORM_LIBS "")
list(APPEND CORE_PLATFORM_LIBS ethosu_uart_cmsdk_apb)